export const SELECT_CHAT = 'APP/CHAT/SELECT'
export const CHAT_SEND_MESSAGE = 'APP/CHAT/MESSAGE/SEND'

export const SIGN_UP_NEXT_STEP = 'APP/SIGNUP/NEXT'
export const SIGN_UP_PREV_STEP = 'APP/SIGNUP/PREV'
export const SIGN_UP_UPDATE_FORM = 'APP/SIGNUP/UPDATE'
